<?php

namespace Database\Seeders;

use App\Models\CommitteeRegistry;
use App\Models\OrdinanceCode;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Committee Registries
        $committees = [
            'Committee on Cooperatives',
            'Committee on Environment',
            'Committee on Finance, Budget and Appropriations',
            'Committee on Human Rights',
            'Committee on Ways and Means',
            'Committee on Youth and Sports Development',
            'Committee on Agriculture and Aquatic Resources',
            'Committee on Barangay Affairs',
            'Committee on Disaster Risk Reduction',
            'Committee on Economic Enterprises',
            'Committee on Education',
            'Committee on Games and Amusement',
            'Committee on General Services and Government Property Management',
            'Committee on Good Governance and Oversight',
            'Committee on Health and Wellness',
            'Committee on Information and Public Affairs',
            'Committee on Land Use, Zoning, and Urban Planning',
            'Committee on Local and International Relations',
            'Committee on Peace and Order and Public Safety',
            'Committee on Public Works and Other Utilities',
            'Committee on Rules, Ethics, Laws, Ordinances and Legal Affairs',
            'Committee on Smart and Sustainable Community',
            'Committee on Social Services',
            'Committee on Tourism, Culture, Arts, and Historical Preservation',
            'Committee on Trade, Commerce, and Industry',
            'Committee on Transportation and Traffic Management',
            'Committee on Urban and Rural Livelihood Development',
            'Committee on Women, Family and Gender and Development',
            'Committee on Workforce Development'
        ];

        foreach ($committees as $committeeName) {
            CommitteeRegistry::firstOrCreate(['name' => $committeeName]);
        }

        // 2. Statuses
        $statuses = [
            ['name' => 'New'],
            ['name' => 'Amendment'],
            ['name' => 'Repeal'],
            ['name' => 'Supersede'],
            ['name' => 'Suspended'],
            ['name' => 'Amended'],
        ];

        DB::table('statuses')->insert($statuses);   

        // 3. Classifications
        $classifications = [
            ['name' => 'Administrative'],
            ['name' => 'Executive'],
        ];
        
        DB::table('classifications')->insert($classifications);

        // 4. Users (Department IDs kept null or specific if you re-add departments later)
        $users = [
            [
                'name' => 'System Admin', 
                'email' => 'admin@gmail.com', 
                'role' => 'system_admin',
                'department_id' => null 
            ],
            [
                'name' => 'Office of the City Administrator', 
                'email' => 'adm@gmail.com', 
                'role' => 'supervisor', 
                'department_id' => null
            ],
            [
                'name' => 'Office of the Sangguniang Panlungsod', 
                'email' => 'osp@gmail.com', 
                'role' => 'supervisor', 
                'department_id' => null
            ],
            [
                'name' => 'Focal Person (Tourism)', 
                'email' => 'focal@gmail.com', 
                'role' => 'focal_person', 
                'department_id' => null 
            ],
            [
                'name' => 'Monitoring Committee', 
                'email' => 'rrt@gmail.com', 
                'role' => 'monitoring_committee',
                'department_id' => null
            ],
            [
                'name' => 'Kent Aldrin Tan', 
                'email' => 'guest@gmail.com', 
                'role' => 'read_only',
                'department_id' => null
            ],
        ];

        foreach ($users as $data) {
            User::factory()->create($data);
        }

        // 5. Ordinance Codes

        $ordinanceCodes = [
            ['name' => 'ADVERTISEMENTS', 'description' => null],
            ['name' => 'ADVERTISEMENTS, SIGNS, SIGNBOARDS, BILLBOARDS', 'description' => null],
            ['name' => 'AGRICULTURE', 'description' => null],
            ['name' => 'AMBULANT/TRANSIENT VENDORS/BARATILLOS (DISTANCE FROM MONUMENTS)', 'description' => null],
            ['name' => 'AMBULANT/TRANSIENT VENDORS/BARATILLOS (DISTANCE FROM WAITING SHEDS)', 'description' => null],
            ['name' => 'AMBULANT/TRANSIENT VENDORS/BARATILLOS (GENERAL RULE)', 'description' => null],
            ['name' => 'AMBULANT/TRANSIENT VENDORS/BARATILLOS (LICENSING)', 'description' => null],
            ['name' => 'AMBULANT/TRANSIENT VENDORS/BARATILLOS (OPERATION OF \'BARATILLOS\')', 'description' => null],
            ['name' => 'AMBULANT/TRANSIENT VENDORS/BARATILLOS (SALE OF FRESH AND DRIED FISH)', 'description' => null],
            ['name' => 'ANIMALS, PROTECTION OF', 'description' => null],
            ['name' => 'AWARDS', 'description' => null],
            ['name' => 'BARANGAY AFFAIRS', 'description' => null],
            ['name' => 'BARS, CABARETS, NIGHT/DAY CLUBS', 'description' => null],
            ['name' => 'BEAUTIFICATION', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (BUILDING CONSTRUCTION FEES)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (CELLULAR SITES)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (DISTANCE FROM CEMETERY)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (DISTANCE FROM THE EDGE OF ALL MUNICIPAL ROADS)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (FENCE)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (GASOLINE AND SERVICE STATIONS)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (MULTI-PURPOSE OFFICE BUILDING)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (ON GENERATORS)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (PROHIBITING CONSTRUCTION OVER ESTEROS)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (SALVAGE ZONES)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (SERVICE FEES BY CONTRACTORS)', 'description' => null],
            ['name' => 'BUILDING/CONSTRUCTION (SIGNS/NOTICES)', 'description' => null],
            ['name' => 'BUS STOP', 'description' => null],
            ['name' => 'CEMETERY', 'description' => null],
            ['name' => 'CENTENARIANS', 'description' => null],
            ['name' => 'CIVIL REGISTRY DOCUMENTS', 'description' => null],
            ['name' => 'COCKFIGHTING/COCKPITS', 'description' => null],
            ['name' => 'COMMUNITY TAX', 'description' => null],
            ['name' => 'COURT FEE', 'description' => null],
            ['name' => 'CREATION OF OFFICES', 'description' => null],
            ['name' => 'CULTURAL', 'description' => null],
            ['name' => 'CURFEW', 'description' => null],
            ['name' => 'EDUCATION', 'description' => null],
            ['name' => 'EDUCATIONAL ASSISTANCE PROGRAM', 'description' => null],
            ['name' => 'ELECTION', 'description' => null],
            ['name' => 'ELECTRICAL CODE', 'description' => null],
            ['name' => 'ELIGIBILITY FOR FISHING AND/OR FISHERY PRIVILEGES', 'description' => null],
            ['name' => 'ENVIRONMENTAL PROTECTION', 'description' => null],
            ['name' => 'EQUIPMENT/VEHICLES', 'description' => null],
            ['name' => 'EXTENSION OF THE TIME OF PAYMENT', 'description' => null],
            ['name' => 'FIESTA', 'description' => null],
            ['name' => 'FIRST AID', 'description' => null],
            ['name' => 'FISHERIES', 'description' => null],
            ['name' => 'FISHERIES (FISHING, REGULATION OF)', 'description' => null],
            ['name' => 'FISHERIES (FIVE (5) ZONES)', 'description' => null],
            ['name' => 'FISHERIES (LICENSE TAXES AND FEES)', 'description' => null],
            ['name' => 'FISHERIES (TIPO OR MINIMUM BID)', 'description' => null],
            ['name' => 'GAMBLING', 'description' => null],
            ['name' => 'GASOLINE SERVICE STATIONS SAFETY REGULATION', 'description' => null],
            ['name' => 'GENDER', 'description' => null],
            ['name' => 'GENDER FAIRNESS', 'description' => null],
            ['name' => 'GENERAL ORDINANCES, CODIFICATION OF', 'description' => null],
            ['name' => 'GOOD GOVERNANCE', 'description' => null],
            ['name' => 'HEALTH (HIV)', 'description' => null],
            ['name' => 'HEALTH (IODIZED SALT)', 'description' => null],
            ['name' => 'HEALTH (ON ANIMALS)', 'description' => null],
            ['name' => 'HEALTH (ON BARBERS)', 'description' => null],
            ['name' => 'HEALTH (ON DRUGS)', 'description' => null],
            ['name' => 'HEALTH (ON FRUITS AND VEGETABLES RIPENED BY CARBIDE)', 'description' => null],
            ['name' => 'HEALTH (OTHERS)', 'description' => null],
            ['name' => 'HUMAN RIGHTS', 'description' => null],
            ['name' => 'INFECTIOUS DISEASE CODE', 'description' => null],
            ['name' => 'JAYWALKING', 'description' => null],
            ['name' => 'LICENSE TO PRACTICE PROFESSION', 'description' => null],
            ['name' => 'LIQUOR', 'description' => null],
            ['name' => 'MANNERS', 'description' => null],
            ['name' => 'MARCOS BUILDING', 'description' => null],
            ['name' => 'MARKET (AIR PRESSURED GAS OR KEROSENE STOVES)', 'description' => null],
            ['name' => 'MARKET (B. STALLS AND SPACES)', 'description' => null],
            ['name' => 'MARKET (CLOSING HOUR)', 'description' => null],
            ['name' => 'MARKET (FEES)', 'description' => null],
            ['name' => 'MARKET (GENERAL)', 'description' => null],
            ['name' => 'MARKET (JUKE BOXES)', 'description' => null],
            ['name' => 'MARKET (ON-NAMING)', 'description' => null],
            ['name' => 'MARKET (PEDDLERS AND PEDDLING)', 'description' => null],
            ['name' => 'MARKET (SANITARY MAINTENANCE)', 'description' => null],
            ['name' => 'MARKET (STALLS AND SPACESB)', 'description' => null],
            ['name' => 'MARKET (TEMPORARY SHADES)', 'description' => null],
            ['name' => 'MARKET (VENDORS)', 'description' => null],
            ['name' => 'MARKET (WET MARKET )', 'description' => null],
            ['name' => 'MARKET(B. STALLS AND SPACESB)', 'description' => null],
            ['name' => 'MARKET(MARKET DAYS)', 'description' => null],
            ['name' => 'NUISANCE(COURT ZONES)', 'description' => null],
            ['name' => 'NUISANCE(LOUD AND UNNECESSARY NOISE)', 'description' => null],
            ['name' => 'NUISANCE(ON ANIMALS)', 'description' => null],
            ['name' => 'NUISANCE(QUIET ZONE)', 'description' => null],
            ['name' => 'NUISANCE(SERENADING AND CAROLING)', 'description' => null],
            ['name' => 'NUMBERING OF HOUSES', 'description' => null],
            ['name' => 'OCCUPATIONAL HEALTH AND SAFETY', 'description' => null],
            ['name' => 'OTHERS', 'description' => null],
            ['name' => 'PARKING REGULATIONS', 'description' => null],
            ['name' => 'PARKING REGULATIONS (LIGHT VEHICLES)', 'description' => null],
            ['name' => 'PARKS MANAGEMENT', 'description' => null],
            ['name' => 'PEACE AND ORDER(RALLIES)', 'description' => null],
            ['name' => 'PENALIZING ILLEGAL TRADE', 'description' => null],
            ['name' => 'PROHIBIT DISCRIMINATION', 'description' => null],
            ['name' => 'PROHIBITING HARASSMENT', 'description' => null],
            ['name' => 'PROMOTE HEALTH AND WELLNESS', 'description' => null],
            ['name' => 'PUBLIC MORALS', 'description' => null],
            ['name' => 'PUBLIC SAFETY (DEADLY WEAPON )', 'description' => null],
            ['name' => 'PUBLIC SAFETY (DISASTER)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (EXPLOSIVES, FIRECRACKERS)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (FIRE EXTINGUISHER)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (FIRE HYDRANTS)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (FIRE ZONES)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (FURNACES, BOILERS, CONDENSERS, GENERATORS AND OTHER MACHINERIES)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (LIFE VESTS)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (LOCAL CELEBRATIONS)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (ON FLAMMABLE SUBSTANCES)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (OTHERS)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (POLICE/MAYOR\'S CLEARANCE)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (PROTECTION OF BUSINESSES)', 'description' => null],
            ['name' => 'PUBLIC SAFETY (REAL PROPERTY TAX )', 'description' => null],
            ['name' => 'PUBLIC SAFETY (REVENUE )', 'description' => null],
            ['name' => 'REGULATION (FIRECRACKERS)', 'description' => null],
            ['name' => 'ROADS (BARRIO ROADS)', 'description' => null],
            ['name' => 'ROADS (NAMING)', 'description' => null],
            ['name' => 'SAFE DRINKING WATER CODE', 'description' => null],
            ['name' => 'SANITATION (SANITATION CODE)', 'description' => null],
            ['name' => 'SLAUGHTER/SLAUGHTERHOUSE', 'description' => null],
            ['name' => 'SMOKE-FREE', 'description' => null],
            ['name' => 'SMOKING', 'description' => null],
            ['name' => 'SOCIAL WELFARE (PERSONS WITH DISABILITIES)', 'description' => null],
            ['name' => 'SOCIAL WELFARE (PHILHEALTH FOR INDIGENTS)', 'description' => null],
            ['name' => 'SOCIAL WELFARE (SENIOR CITIZENS)', 'description' => null],
            ['name' => 'SOLID WASTE MANAGEMENT', 'description' => null],
            ['name' => 'STAFFING PATTERN', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(BATTERIES)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(BICYCLES FOR RENT)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(CHICKENS, PIGS, GOATS, DUCKS, FOWLS, GEESE, EARTHEN POTS)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(CONDITION FOR THE ISSUANCE OF BUSINESS OR MAYOR\'S PERMIT)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(FIREWOOD)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(JUKE BOX)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(LICENSE TO ENGAGE IN BUSINESS)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(MANUFACTURE OF ICE DROP)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(MANUFACTURED MINERAL OILS, MOTOR FUELS, DIESEL FUEL OIL AND OTHER MINERAL OILS)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(PAWNSHOPS)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(SCHOOLS)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(SCRAP IRON)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(SOFT DRINKS)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(TOBACCO)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(TRAVELING PHOTOGRAPHERS)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(UNLOADING GASOLINE, KEROSENE, ALCOHOL OR ANY OTHER INFLAMMABLE SUBSTANCE)', 'description' => null],
            ['name' => 'TAX/LICENSE/PERMIT(VULCANIZING)', 'description' => null],
            ['name' => 'TRADE', 'description' => null],
            ['name' => 'TRADE (AMUSEMENT PLACES, ENTERTAINMENT, DISTANCE FROM)', 'description' => null],
            ['name' => 'TRADE (BAKERIES)', 'description' => null],
            ['name' => 'TRADE (BLUE SUNDAY)', 'description' => null],
            ['name' => 'TRADE (BOARDING HOUSES)', 'description' => null],
            ['name' => 'TRADE (HOTELS)', 'description' => null],
            ['name' => 'TRADE (I. SWEEPSTAKES)', 'description' => null],
            ['name' => 'TRADE (INCENTIVES CODE)', 'description' => null],
            ['name' => 'TRADE (IRECREATION, AMUSEMENT DEVICES AND THE LIKE - BILLIARD AND POOL HALLS)', 'description' => null],
            ['name' => 'TRADE (LPG)', 'description' => null],
            ['name' => 'TRADE (LUMBER YARDS)', 'description' => null],
            ['name' => 'TRADE (MOBILE PHONES)', 'description' => null],
            ['name' => 'TRADE (OPENING AND CLOSING OF STORES)', 'description' => null],
            ['name' => 'TRADE (PNP UNIFORM/INSIGNIAS AND OTHER ACCESSORIES)', 'description' => null],
            ['name' => 'TRADE (PRICE COORDINATING COUNCIL)', 'description' => null],
            ['name' => 'TRADE (PRIVATE DETECTIVE, PROTECTIVE, WATCHMAN AND OTHER SIMILAR AGENCIES)', 'description' => null],
            ['name' => 'TRADE (VIDEOKE MACHINES)', 'description' => null],
            ['name' => 'TRANSPORTATION ( PROHIBITED ACTS AND CORRESPONDING PENALTIES)', 'description' => null],
            ['name' => 'TRANSPORTATION ( STREETS AND SIDEWALKS)', 'description' => null],
            ['name' => 'TRANSPORTATION (2 – 3 WHEELED VEHICLES)', 'description' => null],
            ['name' => 'TRANSPORTATION (ON IDENTIFICATION CARDS)', 'description' => null],
            ['name' => 'TRANSPORTATION (ON LIGHTS)', 'description' => null],
            ['name' => 'TRANSPORTATION (ON PARKING)', 'description' => null],
            ['name' => 'TRANSPORTATION (ON ROAD-RIGHT-OF-WAY OF FIRE TRUCKS)', 'description' => null],
            ['name' => 'TRANSPORTATION (ON ROADS CLOSED TO VEHICULAR TRAFFIC ON CERTAIN DAYS)', 'description' => null],
            ['name' => 'TRANSPORTATION (ON SCHOOL BUSES)', 'description' => null],
            ['name' => 'TRANSPORTATION (ONE-WAY STREETS)', 'description' => null],
            ['name' => 'TRANSPORTATION (OTHER STREETS)', 'description' => null],
            ['name' => 'TRANSPORTATION (OTHERS)', 'description' => null],
            ['name' => 'TRANSPORTATION (OVERLOADING)', 'description' => null],
            ['name' => 'TRANSPORTATION (PROHIBITED ACTS AND CORRESPONDING PENALTIES)', 'description' => null],
            ['name' => 'TRANSPORTATION (SPEED LIMIT - PORO PORT ROAD )', 'description' => null],
            ['name' => 'TRANSPORTATION (TRAFFIC ORDINANCE)', 'description' => null],
            ['name' => 'TRANSPORTATION (TRICYCLES)', 'description' => null],
            ['name' => 'TRANSPORTATION (UTILITIES)', 'description' => null],
            ['name' => 'WATER', 'description' => null],
            ['name' => 'WEBSITES ACCESSIBILITY', 'description' => null],
            ['name' => 'WEIGHTS AND MEASURES', 'description' => null],
            ['name' => 'YOUTH EXCELLENCE ORDINANCE', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (CHILDREN\'S CODE)', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (COMPUTER GAMING/INTERNET CAFES )', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (CURFEW)', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (EMPLOYMENT)', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (LINGGO NG KABATAAN )', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (ON LIQUOR)', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (PROSTITUTION)', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (SMOKING)', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (TOURISM)', 'description' => null],
            ['name' => 'YOUTH/MINORS/CHILDREN (YOUTH DEVELOPMENT COUNCIL)', 'description' => null],
            ['name' => 'ZONING REGULATIONS', 'description' => null],
            ['name' => 'ZONING/LAND USE/CLASSIFICATION', 'description' => null],
            ['name' => 'TRANSPORTATION (NUMBER CODING)', 'description' => null],
            ['name' => 'WOMEN/CHILDREN/VAWC', 'description' => null],
            ['name' => 'WOMEN/COUNCIL FOR WOMEN', 'description' => null],
            ['name' => 'HOUSING/HOUSING BOARD', 'description' => null],
            ['name' => 'WEBSITES/MINORS/INTERNET CAFES/COMPUTER SERVICE/PUBLIC LIBRARIES', 'description' => null],
            ['name' => 'COOPERATIVE/CITY COOPERATIVE AND DEVELOPMENT OFFICE', 'description' => null],
            ['name' => 'BARATILLOS/FLEA MARKETS/NIGHT MARKETS/TRADE FAIRS/SEASONAL BUSINESSES', 'description' => null],
            ['name' => 'HEALTH/INFECTIOUS DISEASE', 'description' => null],
            ['name' => 'HEALTH/WORKPLACE', 'description' => null],
            ['name' => 'HEALTH/TATTOO/BODY PIERCING/ BRANDING/SCARIFICATION', 'description' => null],
            ['name' => 'HEALTH/MENTAL HEALTH', 'description' => null],
            ['name' => 'DRAG RACING/GAMBLING/MOTORCYCLE/ CARS', 'description' => null],
            ['name' => 'GENDER/GENDER EQUALITY/GESI/SOCIAL INCLUSION', 'description' => null],
            ['name' => 'REAL ESTATE', 'description' => null],
            ['name' => 'CONTRABAND/JAILS/DETENTION CELLS/HALF-WAY HOUSE', 'description' => null],
            ['name' => 'HEALTH/DRUGS/DRUG-FREE WORKPLACE/DRUG TESTING', 'description' => null],
            ['name' => 'TRAFFIC/PARKING', 'description' => null],
            ['name' => 'TRANSPORTATION/SPEED LIMIT/MOTOR VEHICLES', 'description' => null],
            ['name' => 'AGRICULTURE/FERTILIZER/SEED SUPPORT/FARMERS', 'description' => null],
            ['name' => 'AGRICULTURE/LIFE INSURANCE/FARMERS/FISHER FOLKS', 'description' => null],
            ['name' => 'INVESTMENTS/INCENTIVES', 'description' => null],
            ['name' => 'TRANSPORTATION/TRICYCLE/FRANCHISE', 'description' => null],
            ['name' => 'INDIGENT CITIZENS', 'description' => null],
            ['name' => 'ENERGY', 'description' => null],
            ['name' => 'SPORTS AND RECREATION DEVELOPMENT', 'description' => null],
            ['name' => 'TAX ORDINANCE', 'description' => null],
            ['name' => 'BAWAL BASTOS', 'description' => null],
            ['name' => 'GENDER (BAWAL BASTOS)', 'description' => null],
            ['name' => 'BARANGAY CLEARANCE', 'description' => null],
            ['name' => 'OFWS', 'description' => null],
            ['name' => 'KAPIHAN', 'description' => null],
            ['name' => 'NON-GOVERNMENT ORGANIZATIONS, ACCREDITATION, PEOPLE\'S COUNCIL (LPC)', 'description' => null],
            ['name' => 'CHILDREN\'S CODE', 'description' => null],
            ['name' => 'VOLUNTEER', 'description' => null],
            ['name' => 'GENERAL ORDINANCE', 'description' => null],
    ];

        DB::table('ordinance_codes')->insert($ordinanceCodes);
    }
}