/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "dashboard": [],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true
        }
    ],
    "statuses.index": [],
    "statuses.create": [],
    "statuses.store": [],
    "statuses.show": [
        {
            "name": "status",
            "required": true
        }
    ],
    "statuses.edit": [
        {
            "name": "status",
            "required": true
        }
    ],
    "statuses.update": [
        {
            "name": "status",
            "required": true
        }
    ],
    "statuses.destroy": [
        {
            "name": "status",
            "required": true
        }
    ],
    "departments.index": [],
    "departments.create": [],
    "departments.store": [],
    "departments.show": [
        {
            "name": "department",
            "required": true
        }
    ],
    "departments.edit": [
        {
            "name": "department",
            "required": true
        }
    ],
    "departments.update": [
        {
            "name": "department",
            "required": true
        }
    ],
    "departments.destroy": [
        {
            "name": "department",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
