<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Legislative Report</title>

    <style>
        * {
            box-sizing: border-box;
        }

        @page {
            margin: 0.5cm;
            size: landscape;
            margin-bottom: 1.5cm;
        }
        
        body {
            font-family: Arial, sans-serif;
            font-size: 9px;
            line-height: 1.2;
            margin: 0;
            padding: 0;
            color: #000;
        }
        
        .report-header { text-align: center; margin-bottom: 15px; }
        .organization { font-size: 13px; margin: 0; }
        .office { font-weight: bold; font-size: 15px; margin: 0; }
        .report-title { font-size: 12px; margin: 3px 0; font-weight: bold; text-transform: uppercase; }
        .report-date { font-size: 9px; margin-bottom: 10px; color: #444; }
        
        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed; /* Forces strict column widths */
        }
        
        thead { display: table-header-group; }
        
        th, td {
            border: 0.5px solid #000;
            padding: 6px;
            vertical-align: middle; 
            text-align: center; /* Centers all text globally */
            font-size: 9px;
            word-wrap: break-word; /* Forces wrapping */
            overflow-wrap: break-word;
        }
        
        th {
            background-color: #e0e0e0;
            font-weight: bold;
        }
        
        /* Widths carefully calculated to equal exactly 100% */
        .w-xs { width: 6%; } 
        .w-sm { width: 10%; } 
        .w-md { width: 18%; }
        .w-lg { width: 23%; }
        .w-date { width: 10%; }
        
    </style>
</head>
<body>
    <div class="report-header">
        <p class="organization">CITY GOVERNMENT OF SAN FERNANDO, LA UNION</p>
        <p class="office">CITY INFORMATION AND COMMUNICATIONS TECHNOLOGY OFFICE</p>
        <p class="report-title">
            @if(isset($filters['type']))
                @if($filters['type'] == 'eo') Executive Orders Report
                @elseif($filters['type'] == 'ordinance') Ordinances Report
                @else Master Legislative Report
                @endif
            @else
                Master Legislative Report
            @endif
        </p>
        <p class="report-date">Generated on: {{ date('F d, Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th class="w-xs">Type</th>          <!-- 6% -->
                <th class="w-sm">Tracking No.</th>  <!-- 10% -->
                <th class="w-xl">Subject Title</th> <!-- 30% -->
                <th class="w-xl">Subject Matter</th><!-- 30% -->
                <th class="w-date">Date</th>        <!-- 12% -->
                <th class="w-sm">Status</th>        <!-- 12% -->
            </tr>
        </thead>
        <tbody>
            @forelse($records as $record)
            <tr>
                <td class="w-xs"><strong>{{ $record['doc_type'] }}</strong></td>
                <td class="w-sm font-mono">{{ $record['tracking_number'] }}</td>
                <td class="w-lg font-bold">{{ $record['title'] }}</td>
                <td class="w-lg">{{ $record['subject_matter'] }}</td>
                <td class="w-date">{{ date('M d, Y', strtotime($record['date'])) }}</td>
                <td class="w-sm"><strong>{{ $record['status_name'] }}</strong></td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="padding: 20px;">No records match your filter criteria.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

<script type="text/php">
    if (isset($pdf)) {
        $font = $fontMetrics->getFont("Arial", "normal");
        $size = 8;
        $pageText = "Executive Orders and Ordinances System | Page {PAGE_NUM} of {PAGE_COUNT} | Generated by: {{ $name }}";
        $width = $fontMetrics->getTextWidth($pageText, $font, $size);
        $x = 20; 
        $y = $pdf->get_height() - 30; 
        $pdf->page_text($x, $y, $pageText, $font, $size);
    }
</script>
</body>
</html>