<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Legislative Report</title>

    <style>
        @page {
            margin: 0.5cm;
            size: landscape;
            margin-bottom: 2cm;
        }
        body {
            font-family: Arial, sans-serif;
            font-size: 9px;
            line-height: 1.2;
            margin: 0;
            padding: 0;
            color: #000;
        }
        .report-header { text-align: center; margin-bottom: 15px; }
        .organization { font-size: 13px; margin: 0; }
        .office { font-weight: bold; font-size: 15px; margin: 0; }
        .report-title { font-size: 12px; margin: 3px 0; font-weight: bold; text-transform: uppercase; }
        .report-date { font-size: 9px; margin-bottom: 10px; color: #444; }
        
        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }
        thead { display: table-header-group; }
        tfoot { display: table-footer-group; }
        th, td {
            border: 0.5px solid #000;
            padding: 4px;
            vertical-align: top;
            font-size: 9px;
        }
        th {
            background-color: #e0e0e0;
            font-weight: bold;
            text-align: center;
        }
        
        /* Column Widths */
        .w-xs { width: 5%; text-align: center; } 
        .w-sm { width: 10%; text-align: center; } 
        .w-md { width: 15%; }
        .w-lg { width: 25%; }
        
        .wrap-text {
            word-break: break-word;
            white-space: normal;
        }
    </style>
</head>
<body>
    <div class="report-header">
        <p class="organization">CITY GOVERNMENT OF SAN FERNANDO, LA UNION</p>
        <p class="office">CITY INFORMATION AND COMMUNICATIONS TECHNOLOGY OFFICE</p>
        <p class="report-title">
            @if(isset($filters['type']))
                @if($filters['type'] == 'eo') Executive Orders Report
                @elseif($filters['type'] == 'ordinance') Ordinances Report
                @else Master Legislative Report
                @endif
            @else
                Master Legislative Report
            @endif
        </p>
        <p class="report-date">Generated on: {{ date('F d, Y h:i A') }}</p>
    </div>

    <div class="overflow-x-auto">
        <table class="min-w-full table-auto">
            <thead>
                <tr>
                    <th class="w-xs">Type</th>
                    <th class="w-sm">Tracking No.</th>
                    <th class="w-lg">Subject Title</th>
                    <th class="w-lg">Subject Matter</th>
                    <th class="w-md">Committee / Author</th>
                    <th class="w-sm">Date</th>
                    <th class="w-sm">Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse($records as $record)
                <tr>
                    <td class="w-xs"><strong>{{ $record['doc_type'] }}</strong></td>
                    <td class="w-sm font-mono">{{ $record['tracking_number'] }}</td>
                    <td class="w-lg wrap-text font-bold">{{ $record['title'] }}</td>
                    <td class="w-lg wrap-text">{{ $record['subject_matter'] }}</td>
                    <td class="w-md wrap-text">{{ $record['involved_parties'] }}</td>
                    <td class="w-sm">{{ date('M d, Y', strtotime($record['date'])) }}</td>
                    <td class="w-sm"><strong>{{ $record['status_name'] }}</strong></td>
                </tr>
                @empty
                <tr>
                    <td class="text-center" colspan="7" style="padding: 20px;">No records match your filter criteria.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

<script type="text/php">
    if (isset($pdf)) {
        $font = $fontMetrics->getFont("Arial", "normal");
        $size = 8;
        $pageText = "SP E-Archives | Page {PAGE_NUM} of {PAGE_COUNT} | Generated by: {{ $name }}";
        $width = $fontMetrics->getTextWidth($pageText, $font, $size);
        $x = 20; // left margin
        $y = $pdf->get_height() - 30; // 30 units from bottom
        $pdf->page_text($x, $y, $pageText, $font, $size);
    }
</script>
</body>
</html>